
CREATE TABLE users (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    active BOOLEAN,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE teams (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL UNIQUE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
CREATE TABLE stat (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    speed INT(2) NOT NULL DEFAULT 50,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE players (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    firstname VARCHAR(50) NOT NULL,
    lastname VARCHAR(50) NOT NULL,
    img VARCHAR(255) NOT NULL,
    team_id INT(11),
    stat_id INT(11),
    pos VARCHAR(50) NOT NULL,
    num VARCHAR(50) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP

)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

ALTER TABLE players
ADD FOREIGN KEY (team_id) REFERENCES teams(id);
ALTER TABLE players
ADD FOREIGN KEY (stat_id) REFERENCES stat(id);


SELECT CONCAT('ALTER TABLE `', t.`TABLE_SCHEMA`, '`.`', t.`TABLE_NAME`, '` CONVERT TO CHARACTER SET utf8mb4_unicode_520_ci COLLATE utf8mb4_general_ci;') as sqlcode
FROM `information_schema`.`TABLES` t
WHERE 1
AND t.`TABLE_SCHEMA` = 'u0365877_football'
ORDER BY 1
ALTER TABLE `u0365877_football`.`players` CONVERT TO CHARACTER SET utf8_unicode_ci COLLATE utf8mb4_general_ci;
ALTER TABLE `u0365877_football`.`stat` CONVERT TO CHARACTER SET utf8_unicode_ci COLLATE utf8mb4_general_ci;
ALTER TABLE `u0365877_football`.`teams` CONVERT TO CHARACTER SET utf8_unicode_ci COLLATE utf8mb4_general_ci;
ALTER TABLE `u0365877_football`.`users` CONVERT TO CHARACTER SET utf8_unicode_ci COLLATE utf8mb4_general_ci;